[package]
name = "application"
version = "0.1.0"
authors = ["Oussama <md.oussama@gmail.com>"]

[dependencies]



[target.'cfg(target_arch = "wasm32")'.dependencies]
stdweb = "*"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "*"